Repository Konijima/PZ-Community-API, pull requests merged in 2021-11, with the labels that each got.

#1 ItemTooltipAPI
  media/lua/client/ItemTooltipAPI/ItemTooltips/base_example.lua
  media/lua/client/ItemTooltipAPI/Main.lua
  media/lua/client/ItemTooltipAPI/Overrides/ISToolTipInv.lua
  media/lua/client/ItemTooltipAPI/README.md
Labels: enhancement

#2 DistributionAPI
  media/lua/server/DistributionAPI/Main.lua
  media/lua/server/DistributionAPI/README.md
Labels: enhancement

#3 BodyLocationsAPI: Adapted for CommunityAPI
  media/lua/shared/BodyLocationsAPI/README.md
  media/lua/shared/BodyLocationsAPI/Shared.lua
Labels: enhancement

#4 Changed the classes structure to return itself
  media/lua/client/ItemTooltipAPI/Client.lua
  media/lua/client/ItemTooltipAPI/ItemTooltips/base_example.lua
  media/lua/client/ItemTooltipAPI/Overrides/ISToolTipInv.lua
  media/lua/client/ItemTooltipAPI/README.md
  media/lua/server/DistributionAPI/README.md
  media/lua/server/DistributionAPI/Server.lua
Labels: enhancement

#9 LightAPI: Added template files for the new API.
  media/lua/client/CommunityAPI.lua
  media/lua/client/LightAPI/Client.lua
  media/lua/client/LightAPI/README.md
Labels: enhancement

#8 WorldSoundAPI: Added template files for the new API.
  media/lua/client/CommunityAPI.lua
  media/lua/client/WorldSoundAPI/Client.lua
  media/lua/client/WorldSoundAPI/README.md
Labels: enhancement

#7 IsoRangeScanAPI: Added template files for the new API.
  media/lua/client/CommunityAPI.lua
  media/lua/client/IsoRangeScanAPI/Client.lua
  media/lua/client/IsoRangeScanAPI/README.md
Labels: enhancement

#6 SpawnerAPI: Added template files for the new API.
  media/lua/client/CommunityAPI.lua
  media/lua/client/SpawnerAPI/Client.lua
  media/lua/client/SpawnerAPI/README.md
  media/lua/server/CommunityAPI.lua
  media/lua/server/SpawnerAPI/README.md
  media/lua/server/SpawnerAPI/Server.lua
Labels: enhancement

#11 LightAPI: Added code
  media/lua/client/LightAPI/Client.lua
Labels: enhancement

#10 Initial Version of SpawnerAPI
  media/lua/client/CommunityAPI.lua
  media/lua/client/SpawnerAPI/Client.lua
  media/lua/client/SpawnerAPI/README.md
  media/lua/client/SpawnerAPI/SpawnerAPIClient.lua
Labels: enhancement

#13 WorldSoundAPI: Added code
  media/lua/client/WorldSoundAPI/README.md
  media/lua/client/WorldSoundAPI/WorldSoundAPIClient.lua
Labels: enhancement

#12 SpawnerAPI: Changed the modData structure
  media/lua/client/SpawnerAPI/SpawnerAPIClient.lua
Labels: enhancement

#15 Utilities: Added and changed IsoRange functions
  media/lua/client/CommunityAPI.lua
  media/lua/client/IsoRangeScanAPI/IsoRangeScanAPIClient.lua
  media/lua/client/IsoRangeScanAPI/README.md
  media/lua/shared/CommunityAPI/README.md
  media/lua/shared/CommunityAPI/Utilities.lua
Labels: enhancement

#16 Update isoRange
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/Utilities.lua
Labels: enhancement

#18 Update CodingConvention.md
  CodingConvention.md
Labels: documentation

#20 Create main.yml - Upload Action
  .github/workflows/main.yml
Labels: enhancement

#17 Utiltity: Restructure
  Contents/mods/CommunityAPI/media/lua/client/ItemTooltipAPI/ItemTooltipAPIClient.lua
  Contents/mods/CommunityAPI/media/lua/client/ItemTooltipAPI/Overrides/ISToolTipInv.lua
  Contents/mods/CommunityAPI/media/lua/client/ItemTooltipAPI/README.md
  Contents/mods/CommunityAPI/media/lua/client/LightAPI/LightAPIClient.lua
  Contents/mods/CommunityAPI/media/lua/client/LightAPI/README.md
  Contents/mods/CommunityAPI/media/lua/client/SpawnerAPI/README.md
  Contents/mods/CommunityAPI/media/lua/client/SpawnerAPI/SpawnerAPIClient.lua
  Contents/mods/CommunityAPI/media/lua/client/WorldSoundAPI/README.md
  Contents/mods/CommunityAPI/media/lua/client/WorldSoundAPI/WorldSoundAPIClient.lua
  Contents/mods/CommunityAPI/media/lua/server/DistributionAPI/DistributionAPIServer.lua
  Contents/mods/CommunityAPI/media/lua/server/DistributionAPI/README.md
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/ColorUtils.lua
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/InventoryUtils.lua
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/IsoUtils.lua
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/MathUtils.lua
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/README.md
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/StringUtils.lua
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/TableUtils.lua
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/Utilities.lua
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPIShared.lua
Labels: documentation, enhancement

#21 Fixes to main.yml
  .github/workflows/main.yml
Labels: enhancement

#24 Correct comments for spawning functions
  Contents/mods/CommunityAPI/media/lua/client/SpawnerAPI/SpawnerAPIClient.lua
Labels: documentation

#26 Readme update
  README.md
Labels: documentation

#28 Update README.md + Add logos
  Images/discord.png
  Images/workshop.png
  README.md
Labels: documentation

#27 Create a new EventAPI to use in API and Mods
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPIShared.lua
  Contents/mods/CommunityAPI/media/lua/shared/EventAPI/EventAPIShared.lua
  Contents/mods/CommunityAPI/media/lua/shared/EventAPI/README.md
  README.md
Labels: documentation, enhancement

#30 Update DistributionAPI documentation
  Contents/mods/CommunityAPI/media/lua/server/DistributionAPI/README.md
Labels: documentation

#36 CodingConvention documentation update
  CodingConvention.md
Labels: documentation

#31 Update LightAPI documentation
  Contents/mods/CommunityAPI/media/lua/client/LightAPI/README.md
Labels: documentation

#32 Update ItemTooltipAPI doc and small changes
  Contents/mods/CommunityAPI/media/lua/client/ItemTooltipAPI/ItemTooltipAPIClient.lua
  Contents/mods/CommunityAPI/media/lua/client/ItemTooltipAPI/README.md
Labels: documentation

#38 Utils Updated Documentation + Integrated Lua Json
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/InventoryUtils.lua
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/IsoUtils.lua
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/JsonUtils.lua
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/MathUtils.lua
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/README.md
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/StringUtils.lua
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/TableUtils.lua
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPIShared.lua
Labels: documentation, enhancement

#37 EventAPI: Updated the documentation to use proper md table.
  Contents/mods/CommunityAPI/media/lua/shared/EventAPI/README.md
Labels: documentation

#41 SpawnerAPI: Fix check for array is nil
  Contents/mods/CommunityAPI/media/lua/client/SpawnerAPI/SpawnerAPIClient.lua
Labels: fix

#42 EventAPI: Change to use LuaEventManager
  Contents/mods/CommunityAPI/media/lua/shared/EventAPI/EventAPIShared.lua
Labels: enhancement

#34 Added Issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#43 Mod setting API + sandbox settings
  .gitignore
  Contents/mods/CommunityAPI/media/lua/client/CommunityAPI.lua
  Contents/mods/CommunityAPI/media/lua/client/ModSettingAPI/ModSandboxSetting.lua
  Contents/mods/CommunityAPI/media/lua/client/ModSettingAPI/ModSetKeyBindDialog.lua
  Contents/mods/CommunityAPI/media/lua/client/ModSettingAPI/ModSetting.lua
  Contents/mods/CommunityAPI/media/lua/client/ModSettingAPI/ModSettingAPIClient.lua
  Contents/mods/CommunityAPI/media/lua/client/ModSettingAPI/ModSettingHorizontalLine.lua
  Contents/mods/CommunityAPI/media/lua/client/ModSettingAPI/ModSettingPanel.lua
  Contents/mods/CommunityAPI/media/lua/client/ModSettingAPI/ModSettingValueType.lua
  Contents/mods/CommunityAPI/media/lua/client/ModSettingAPI/SandboxSettingPanel.lua
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/IsoUtils.lua
Labels: enhancement

#48 TableUtils: fix EmmyLua param error
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/TableUtils.lua
Labels: documentation

#47 StringUtils: Fix EmmyLua param error
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/StringUtils.lua
Labels: documentation

#46 Iso Utils: fix emmyLua param error
  Contents/mods/CommunityAPI/media/lua/shared/CommunityAPI/IsoUtils.lua
Labels: documentation

#44 World sound api: fix emmy lua param error
  Contents/mods/CommunityAPI/media/lua/client/WorldSoundAPI/WorldSoundAPIClient.lua
Labels: documentation

#51 Reordered ModSetting in alphabetical order
  Contents/mods/CommunityAPI/media/lua/client/CommunityAPI.lua
Labels: fix

#52 Updated annotations issue #50
  Contents/mods/CommunityAPI/media/lua/client/ModSettingAPI/ModSettingAPIClient.lua
  Contents/mods/CommunityAPI/media/lua/client/ModSettingAPI/ModSettingPanel.lua
  Contents/mods/CommunityAPI/media/lua/client/ModSettingAPI/SandboxSettingPanel.lua
Labels: documentation, enhancement

#33 Added Expanded Mod Selector
  Contents/mods/CommunityAPI/media/lua/client/ExpandedModSelector/ModInfoPanel.lua
  Contents/mods/CommunityAPI/media/lua/client/ExpandedModSelector/ModListBox.lua
  Contents/mods/CommunityAPI/media/lua/client/ExpandedModSelector/ModPosterPanel.lua
  Contents/mods/CommunityAPI/media/lua/client/ExpandedModSelector/ModSelector.lua
  Contents/mods/CommunityAPI/media/lua/client/ExpandedModSelector/ModThumbnailPanel.lua
  Contents/mods/CommunityAPI/media/lua/client/ExpandedModSelector/README.md
  Contents/mods/CommunityAPI/media/lua/shared/Translate/EN/UI_EN.txt
  Contents/mods/CommunityAPI/media/lua/shared/Translate/RU/UI_RU.txt
  Contents/mods/CommunityAPI/media/ui/ExpandedModSelector/DefaultIcon.png
  Contents/mods/CommunityAPI/media/ui/ExpandedModSelector/MapIcon.png
Labels: enhancement

#53 Fixed the method names
  Contents/mods/CommunityAPI/media/lua/client/ExpandedModSelector/ModSelector.lua
Labels: bug, fix

#57 Added new collaborators and modsetting api
  README.md
Labels: documentation

#54 ModNewsAPI
  Contents/mods/CommunityAPI/media/lua/client/CommunityAPI.lua
  Contents/mods/CommunityAPI/media/lua/client/ModNewsAPI/ModNewsAPIClient.lua
  Contents/mods/CommunityAPI/media/lua/client/ModNewsAPI/ModNewsButton.lua
  Contents/mods/CommunityAPI/media/lua/client/ModNewsAPI/ModNewsPanel.lua
  Contents/mods/CommunityAPI/media/lua/client/ModNewsAPI/README.md
  Contents/mods/CommunityAPI/media/lua/shared/Translate/EN/UI_EN.txt
  Contents/mods/CommunityAPI/media/lua/shared/Translate/RU/UI_RU.txt
  Contents/mods/CommunityAPI/media/ui/ModNews/notifyIcon.png
Labels: enhancement
